language: python
python:
  - 3.6.7
script:
  - python -m pytest -v tests/unittests.py
  - pip install -r requirements.txt
notifications:
  email:
    recipients:
      - sideshowbobgot@gmail.com
    on_success: never
    on_failure: always