language: python
python:
  - 3.6.7
script:
  - pip install -r requirements.txt
  - python -m pytest -v tests/views_login_unittests.py
  - python -m pytest -v tests/views_users_unittests.py
  - python -m pytest -v tests/views_employees_unittests.py
  - python -m pytest -v tests/views_departments_unittests.py
  - python -m pytest -v tests/rest_users_unittest.py
  - python -m pytest -v tests/rest_employees_unittests.py
  - python -m pytest -v tests/rest_departments_unittests.py

notifications:
  email:
    recipients:
      - sideshowbobgot@gmail.com
    on_success: never
    on_failure: always