language: python
python:
  - 3.6.7
script:
  - pip install -r requirements.txt
  - python -m pytest -v tests/views_Login_unittests.py
  - python -m pytest -v tests/views_Users_unittests.py
  - python -m pytest -v tests/views_Employees_unittests.py
  - python -m pytest -v tests/views_Departments_unittests.py
  - python -m pytest -v tests/rest_Users_unittest.py

notifications:
  email:
    recipients:
      - sideshowbobgot@gmail.com
    on_success: never
    on_failure: always